name: SonarQube Pipeline

on:
  push:
    branches:
      - main

jobs:
  sonarqube-analysis:
    # IMPORTANT:
    # This pipeline is intended to run on a self-hosted runner
    # because SonarQube is hosted locally (localhost:9000)
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build and run SonarQube analysis
        working-directory: ./backend
        run: |
          mvn clean verify \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=com.ris:Moji-recepti \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
